### ISSUE TITLE
Build fails if there are no posts

### ISSUE THREAD

**Issue by sambaldwin** [sb-ph/portfolio-starter#27]
```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: _site/feed.xml

`TemplateWriterWriteError` was thrown
> (_includes/layouts/feed.njk)
  Error: Collection is empty in rssLastUpdatedDate filter.
```

**Comment by piperhaywood** [comment]
@sambaldwin This is sorted. The RSS link is not included in the `head` if there are no posts, and the RSS file has no content if no posts. I couldn’t find a way to not generate the file if no posts though, so it results in an empty XML page. I think this should be sufficient, please close this if you agree.
